/*
-- Query: SELECT * FROM library_management_trial.books
LIMIT 0, 1000

-- Date: 2021-02-23 09:37
*/
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (100,'Python','Geudo','python');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (101,'Python_advanced','Geudo','python');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (102,'Python_deeplearning','Mark Lutz','python');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (103,'Python cook book','Brian','python');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (104,'Learn python the heard way','Zed shaw','python');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (105,'Automate Boring statement','AI sweigart','python');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (106,'History of England, Foundation','Ackroyd, Peter','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (107,'Artist and the Mathematician, The','Aczel, Amir','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (108,'False Impressions','Archer, Jeffery','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (109,'Prisoner of Birth, A','Archer, Jeffery','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (110,'Title','Author','Genre');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (111,'One','Bach, Richard','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (112,'Mossad','Baz-Zohar, Michael','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (113,'Complete Mastermind, The','BBC','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (114,'Men of Mathematics','Bell, E T','mathematics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (115,'Electric Universe','Bodanis, David','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (116,'Learning OpenCV','Bradsky, Gary','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (117,'To Sir With Love','Braithwaite','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (118,'Angels & Demons','Brown, Dan','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (119,'Angels & Demons','Brown, Dan','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (120,'Outsider, The','Camus, Albert','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (121,'Hidden Connections, The','Capra, Fritjof','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (122,'Tao of Physics, The','Capra, Fritjof','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (123,'Uncommon Wisdom','Capra, Fritjof','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (124,'Machine Learning for Hackers','Conway, Drew','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (125,'Jim Corbett Omnibus','Corbett, Jim','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (126,'Introduction to Algorithms','Cormen, Thomas','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (127,'Jurassic Park','Crichton, Michael','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (128,'Beyond the Three Seas','Dalrymple, William','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (129,'City of Djinns','Dalrymple, William','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (130,'Last Mughal, The','Dalrymple, William','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (131,'Oxford book of Modern Science Writing','Dawkins, Richard','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (132,'Beautiful and the Damned, The','Deb, Siddhartha','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (133,'Batatyachi Chal','Deshpande P L','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (134,'Hafasavnuk','Deshpande P L','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (135,'Urlasurla','Deshpande P L','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (136,'Aghal Paghal','Deshpande, P L','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (137,'Apulki','Deshpande, P L','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (138,'Asami Asami','Deshpande, P L','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (139,'Char Shabda','Deshpande, P L','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (140,'Gun Gayin Awadi','Deshpande, P L','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (141,'Radiowaril Bhashane & Shrutika','Deshpande, P L','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (142,'Vyakti ani Valli','Deshpande, P L','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (143,'Ahe Manohar Tari','Deshpande, Sunita','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (144,'Numbers Behind Numb3rs, The','Devlin, Keith','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (145,'Christmas Carol, A','Dickens, Charles','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (146,'Ropemaker, The','Dickinson, Peter','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (147,'Crime and Punishment','Dostoevsky, Fyodor','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (148,'Idiot, The','Dostoevsky, Fyodor','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (149,'Think Complexity','Downey, Allen','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (150,'Complete Sherlock Holmes, The - Vol I','Doyle, Arthur Conan','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (151,'Complete Sherlock Holmes, The - Vol II','Doyle, Arthur Conan','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (152,'Age of Discontuinity, The','Drucker, Peter','economics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (153,'New Markets & Other Essays','Drucker, Peter','economics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (154,'Freakonomics','Dubner, Stephen','economics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (155,'Superfreakonomics','Dubner, Stephen','economics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (156,'Pattern Classification','Duda, Hart','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (157,'Story of Philosophy, The','Durant, Will','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (158,'Rosy is My Relative','Durrell, Gerald','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (159,'Dylan on Dylan','Dylan, Bob','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (160,'Image Processing with MATLAB','Eddins, Steve','signal_processing');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (161,'Age of Wrath, The','Eraly, Abraham','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (162,'Surely You\'re Joking Mr Feynman','Feynman, Richard','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (163,'Age of the Warrior, The','Fisk, Robert','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (164,'Great War for Civilization, The','Fisk, Robert','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (165,'Pillars of the Earth, The','Follett, Ken','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (166,'Data Smart','Foreman, John','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (167,'Computer Vision, A Modern Approach','Forsyth, David','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (168,'Deceiver, The','Forsyth, Frederick','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (169,'Phantom of Manhattan, The','Forsyth, Frederick','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (170,'Veteran, The','Forsyth, Frederick','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (171,'Design with OpAmps','Franco, Sergio','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (172,'From Beirut to Jerusalem','Friedman, Thomas','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (173,'Case of the Lame Canary, The','Gardner, Earle Stanley','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (174,'Maqta-e-Ghalib','Garg, Sanjay','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (175,'Sea of Poppies','Ghosh, Amitav','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (176,'Information, The','Gleick, James','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (177,'Doctor in the Nude','Gordon, Richard','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (178,'Doctor on the Brain','Gordon, Richard','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (179,'Fundamentals of Wavelets','Goswami, Jaideva','signal_processing');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (180,'Econometric Analysis','Greene, W. H.','economics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (181,'Brethren, The','Grisham, John','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (182,'Soft Computing & Intelligent Systems','Gupta, Madan','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (183,'Raisin in the Sun, A','Hansberry, Lorraine','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (184,'Free Will','Harris, Sam','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (185,'God Created the Integers','Hawking, Stephen','mathematics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (186,'Theory of Everything, The','Hawking, Stephen','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (187,'Neural Networks','Haykin, Simon','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (188,'Physics & Philosophy','Heisenberg, Werner','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (189,'Catch 22','Heller, Joseph','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (190,'Farewell to Arms, A','Hemingway, Ernest','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (191,'Mein Kampf','Hitler, Adolf','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (192,'Hunchback of Notre Dame, The','Hugo, Victor','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (194,'Eyeless in Gaza','Huxley, Aldous','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (195,'Talking Straight','Iacoca, Lee','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (196,'Data Analysis with Open Source Tools','Janert, Phillip','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (197,'Trial, The','Kafka, Frank','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (198,'Manasa','Kale, V P','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (199,'Let Us C','Kanetkar, Yashwant','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (200,'Pointers in C','Kanetkar, Yashwant','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (201,'Arthashastra, The','Kautiyla','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (202,'How to Think Like Sherlock Holmes','Konnikova, Maria','psychology');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (203,'City of Joy, The','Lapierre, Dominique','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (204,'Freedom at Midnight','Lapierre, Dominique','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (205,'O Jerusalem!','Lapierre, Dominique','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (206,'Girl who kicked the Hornet\'s Nest','Larsson, Steig','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (207,'Girl who played with Fire','Larsson, Steig','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (208,'Girl with the Dragon Tattoo','Larsson, Steig','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (209,'Prince, The','Machiavelli','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (210,'Ashenden of The British Agent','Maugham, William S','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (211,'Maugham\'s Collected Short Stories, Vol 3','Maugham, William S','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (212,'Moon and Sixpence, The','Maugham, William S','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (213,'Trembling of a Leaf, The','Maugham, William S','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (214,'Python for Data Analysis','McKinney, Wes','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (215,'Integration of the Indian States','Menon, V P','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (216,'Drunkard\'s Walk, The','Mlodinow, Leonard','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (217,'Power Electronics - Mohan','Mohan, Ned','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (218,'Half A Life','Naipaul, V S','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (219,'In a Free State','Naipaul, V. S.','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (220,'India\'s Legal System','Nariman','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (221,'Scoop!','Nayar, Kuldip','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (222,'Discovery of India, The','Nehru, Jawaharlal','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (223,'Data Mining Handbook','Nisbet, Robert','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (224,'Making Software','Oram, Andy','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (225,'Animal Farm','Orwell, George','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (226,'Down and Out in Paris & London','Orwell, George','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (227,'We the Nation','Palkhivala','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (228,'We the People','Palkhivala','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (229,'Last Lecture, The','Pausch, Randy','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (230,'Zen & The Art of Motorcycle Maintenance','Pirsig, Robert','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (231,'Tales of Mystery and Imagination','Poe, Edgar Allen','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (232,'Statistical Decision Theory\'','Pratt, John','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (233,'Ayn Rand Answers','Rand, Ayn','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (234,'Philosophy: Who Needs It','Rand, Ayn','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (235,'Return of the Primitive','Rand, Ayn','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (236,'We the Living','Rand, Ayn','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (237,'Justice, Judiciary and Democracy','Ranjan, Sudhanshu','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (238,'Power Electronics - Rashid','Rashid, Muhammad','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (239,'Cathedral and the Bazaar, The','Raymond, Eric','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (240,'Tales of Beedle the Bard','Rowling, J K','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (241,'History of Western Philosophy','Russell, Bertrand','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (242,'On Education','Russell, Bertrand','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (243,'Unpopular Essays','Russell, Bertrand','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (244,'Empire of the Mughal - Brothers at War','Rutherford, Alex','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (245,'Empire of the Mughal - Raiders from the North','Rutherford, Alex','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (246,'Empire of the Mughal - Ruler of the World','Rutherford, Alex','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (247,'Empire of the Mughal - The Serpent\'s Tooth','Rutherford, Alex','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (248,'Empire of the Mughal - The Tainted Throne','Rutherford, Alex','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (249,'Broca\'s Brain','Sagan, Carl','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (250,'Orientalism','Said, Edward','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (251,'More Tears to Cry','Sassoon, Jean','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (252,'Data Scientists at Work','Sebastian Gutierrez','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (253,'Argumentative Indian, The','Sen, Amartya','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (254,'Idea of Justice, The','Sen, Amartya','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (255,'Identity & Violence','Sen, Amartya','philosophy');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (256,'Rationality & Freedom','Sen, Amartya','economics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (257,'Image Processing & Mathematical Morphology','Shih, Frank','signal_processing');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (258,'Signal and the Noise, The','Silver, Nate','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (259,'Code Book, The','Singh, Simon','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (260,'Simpsons & Their Mathematical Secrets','Singh, Simon','science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (261,'Wealth of Nations, The','Smith, Adam','economics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (262,'Courtroom Genius, The','Sorabjee','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (263,'Burning Bright','Steinbeck, John','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (264,'Grapes of Wrath, The','Steinbeck, John','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (265,'Journal of a Novel','Steinbeck, John','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (266,'Life in Letters, A','Steinbeck, John','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (267,'Moon is Down, The','Steinbeck, John','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (268,'Once There Was a War','Steinbeck, John','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (269,'Russian Journal, A','Steinbeck, John','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (270,'Winter of Our Discontent, The','Steinbeck, John','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (271,'Textbook of Economic Theory','Stonier, Alfred','economics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (272,'Amulet of Samarkand, The','Stroud, Jonathan','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (274,'Data Structures Using C & C++','Tanenbaum, Andrew','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (275,'Analysis, Vol I','Tao, Terence','mathematics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (276,'Structure and Randomness','Tao, Terence','mathematics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (277,'Principles of Communication Systems','Taub, Schilling','computer_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (278,'Bookless in Baghdad','Tharoor, Shashi','nonfiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (279,'Great Indian Novel, The','Tharoor, Shashi','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (280,'India from Midnight to Milennium','Tharoor, Shashi','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (281,'Elements of Information Theory','Thomas, Joy','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (282,'Nature of Statistical Learning Theory, The','Vapnik, Vladimir','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (283,'Statistical Learning Theory','Vapnik, Vladimir','data_science');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (284,'Social Choice & Welfare, Vol 39 No. 1','Various','economics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (285,'20000 Leagues Under the Sea','Verne, Jules','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (286,'Birth of a Theorem','Villani, Cedric','mathematics');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (287,'Slaughterhouse Five','Vonnegut, Kurt','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (288,'Short History of the World, A','Wells, H G','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (289,'New Machiavelli, The','Wells, H. G.','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (290,'Devil\'s Advocate, The','West, Morris','fiction');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (291,'All the President\'s Men','Woodward, Bob','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (292,'Veil: Secret Wars of the CIA','Woodward, Bob','history');
INSERT INTO `` (`Book_id`,`Book_name`,`Book_author`,`Genre`) VALUES (293,'Dongri to Dubai','Zaidi, Hussain','nonfiction');
